name: Tests

on:
  push:
    # branches:
    # - master
  pull_request:
    branches:
    - master
  # Run weekly at 1:23 UTC
  schedule:
  - cron: '23 1 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-latest, windows-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v3

      - name: Install test prerequisites
        run: |
          # uv pip install --system cython
          uv pip install --system --upgrade ".[tests]"

      - name: Run tests
        run: pytest --verbose tests/
